test_login.py:
  TestLogin:
    test_login:
      name: login
      scope: session
      depends:

test_home_page.py:
  TestHomePage:
    test_switch_layer:
      name: switch_layer
      scope: session
      depends: [ login ]